//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserService
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public string ServiceDescription { get; set; }
        public int CountryId { get; set; }
        public int StateId { get; set; }
        public int LGAId { get; set; }
        public string FullAddress { get; set; }
        public string Images { get; set; }
        public string UserId { get; set; }
        public string ServiceName { get; set; }
    }
}
