//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Reason { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string RegCode { get; set; }
    }
}
